# Generated by Django 3.0.3 on 2020-03-25 06:50

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200310_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='PhoneNo',
            field=models.CharField(default='1234567890', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)], verbose_name='Phone number'),
        ),
    ]
