# Generated by Django 3.0.3 on 2020-04-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200325_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='pending', max_length=100),
            preserve_default=False,
        ),
    ]
